extraction:
  cpp:
    prepare:
      packages:
        - bison
        - cmake
        - flex
        - g++
        - git
        - libelf-dev
        - libgtest-dev
        - libgmock-dev
        - zlib1g-dev
        - libfl-dev
        - libcereal-dev
        - libdw-dev
        - libpcap-dev
        - systemtap-sdt-dev
        - binutils-dev
        - llvm-11
        - llvm-11-dev
        - llvm-11-runtime
        - libllvm11
        - clang-11
        - libclang-11-dev
        - libclang-common-11-dev
        - libclang1-11
        - libbpfcc-dev
        - systemtap-sdt-dev
        - python3
        - python3-distutils
        - xxd
        - libssl-dev
        - pkg-config
        - make
    configure:
      command:
      - mkdir $LGTM_SRC/build && cd $LGTM_SRC/build
      - export LLVM_ROOT=/usr/lib/llvm-11; export LLVM_REQUESTED_VERSION=11;
      - ../build-libs.sh
      - cmake ..
    index:
      build_command:
      - cd $LGTM_SRC/build
      - make -j$(nproc)
